#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: $0 <app-root> <output-appimage> <appimage-builder-path> <app-version>" >&2
}

if [[ $# -lt 4 ]]; then
    usage
    exit 2
fi

app_root="$1"
output_appimage="$2"
appimage_builder_path="$3"
app_version="$4"
shift 4

if [[ ! -d "$app_root" ]]; then
    echo "App root not found: $app_root" >&2
    exit 1
fi

if [[ -z "$app_version" ]]; then
    echo "App version must not be empty." >&2
    exit 2
fi

if [[ -z "$appimage_builder_path" ]]; then
    appimage_builder_path="$(command -v appimage-builder || true)"
fi

if [[ ! -x "$appimage_builder_path" ]]; then
    if command -v appimage-builder >/dev/null 2>&1; then
        appimage_builder_path="$(command -v appimage-builder)"
    else
        echo "appimage-builder is not executable: $appimage_builder_path" >&2
        exit 1
    fi
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=linux-shortcut-definition.sh
source "$script_dir/linux-shortcut-definition.sh"

recipe_template="$script_dir/AppImageBuilderRecipe.yaml"
if [[ ! -f "$recipe_template" ]]; then
    echo "AppImage builder recipe is missing: $recipe_template" >&2
    exit 1
fi

work_dir="$(mktemp -d "${TMPDIR:-/tmp}/nuvio-appimage.XXXXXX")"
cleanup() {
    rm -rf "$work_dir"
}
trap cleanup EXIT

app_dir="$work_dir/AppDir"
compat_app_dir="$work_dir/Nuvio.AppDir"
echo "App root: $app_root"
echo "Staging AppDir: $app_dir"
echo "Compatibility AppDir: $compat_app_dir"
mkdir -p "$app_dir" "$compat_app_dir"
cp -a "$app_root"/. "$app_dir/"
cp -a "$app_root"/. "$compat_app_dir/"

echo "Copied app payload into $app_dir and $compat_app_dir"

desktop_file="$app_dir/${NUVIO_LINUX_SHORTCUT_NAME}.desktop"
nuvio_linux_write_desktop_entry_file "$desktop_file" "AppRun" "$NUVIO_LINUX_SHORTCUT_NAME"

icon_source="$app_dir/lib/Nuvio.png"
if [[ ! -f "$icon_source" ]]; then
    echo "Expected AppImage icon at $icon_source" >&2
    exit 1
fi
cp "$icon_source" "$app_dir/${NUVIO_LINUX_SHORTCUT_NAME}.png"
ln -sf "${NUVIO_LINUX_SHORTCUT_NAME}.png" "$app_dir/.DirIcon"

resolved_executable=""
search_candidates=(
    "$app_dir/bin/Nuvio"
    "$app_dir/bin/nuvio"
    "$app_dir/Nuvio"
    "$app_dir/nuvio"
    "$compat_app_dir/bin/Nuvio"
    "$compat_app_dir/bin/nuvio"
    "$compat_app_dir/Nuvio"
    "$compat_app_dir/nuvio"
    "$app_root/bin/Nuvio"
    "$app_root/bin/nuvio"
    "$app_root/Nuvio"
    "$app_root/nuvio"
)
while IFS= read -r -d '' candidate; do
    search_candidates+=("$candidate")
done < <(find "$app_dir" -type f \( -name 'Nuvio' -o -name 'nuvio' \) -perm /111 -print0 2>/dev/null)

for candidate in "${search_candidates[@]}"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
        resolved_executable="$candidate"
        break
    fi
done

if [[ -z "$resolved_executable" ]]; then
    echo "Could not locate runnable Nuvio executable beneath $app_root or $app_dir. Searched:" >&2
    for candidate in "${search_candidates[@]}"; do
        echo "  - $candidate" >&2
    done
    exit 1
fi

echo "Resolved executable: $resolved_executable"

echo "AppRun will be generated by appimage-builder for: $resolved_executable"

mkdir -p "$(dirname "$output_appimage")"
recipe_file="$work_dir/AppImageBuilderRecipe.yaml"
cp "$recipe_template" "$recipe_file"

sed -i "s|0.0.0|$app_version|" "$recipe_file"
# appimage-builder resolves variables from the recipe; keep the file name concrete for the generated artifact
sed -i "s|\${APP_VERSION}|$app_version|g" "$recipe_file"

(cd "$work_dir" && ARCH=x86_64 "$appimage_builder_path" --skip-test --recipe "$recipe_file")

generated_appimage="$work_dir/Nuvio-Linux-x86_64-${app_version}.AppImage"
if [[ ! -f "$generated_appimage" ]]; then
    echo "Expected generated AppImage was not produced: $generated_appimage" >&2
    find "$work_dir" -maxdepth 2 -type f -name '*.AppImage' | sort >&2 || true
    exit 1
fi
cp "$generated_appimage" "$output_appimage"

generated_zsync="${generated_appimage}.zsync"
if [[ -f "$generated_zsync" ]]; then
    cp "$generated_zsync" "${output_appimage}.zsync"
fi

if [[ ! -f "$output_appimage" ]]; then
    echo "Expected AppImage output was not produced: $output_appimage" >&2
    exit 1
fi

chmod +x "$output_appimage"
printf 'Built AppImage artifact: %s\n' "$output_appimage"